export const contextTypes = ['objectComment', 'npcComment', 'mobComment', 'loadingComment', 'banter', 'loreExposition', 'rpgDialogue', 'reactions', 'cutscenes', 'quests']

export const entityPrototypes = [
    {
        type: 'scene',
        name: 'My Scene',
        shortname: 'scene#234',
        enabled: true,
        description: 'This is a description of my scene',
        id: '234',
    },
    {
        type: 'character',
        name: 'My Character',
        shortname: 'character#234',
        enabled: true,
        description: 'This is a description of my character',
        inventory: [],
        id: '234',
    },
    {
        type: 'object',
        name: 'My Object',
        shortname: 'object#234',
        enabled: true,
        description: 'This is a description of my object',
        id: '234',
    },
    {
        type: 'npc',
        name: 'My NPC',
        shortname: 'npc#234',
        enabled: true,
        description: 'This is a description of my NPC',
        inventory: [],
        id: '234',
    },
    {
        type: 'mob',
        name: 'My Mob',
        shortname: 'mob#234',
        enabled: true,
        description: 'This is a description of my mob',
        inventory: [],
        id: '234',
    }
]

export const defaultEntityData = {
    dialog: {
        objectComment: ['example object comment'],
        npcComment: ['example npc comment'],
        mobComment: ['example mob comment'],
        loadingComment: ['example loading comment'],
        banter: ['example banter'],
        loreExposition: ['example lore exposition'],
        rpgDialogue: ['example rpg dialogue'],
        reactions: ['example reactions'],
        cutscenes: ['example cutscenes'],
        quests: ['example quests']
    },
    scene: [{
        type: 'scene',
        name: 'My Scene',
        shortname: 'scene#234',
        enabled: true,
        description: 'This is a description of my scene',
        inventory: [],
        id: '234',
    }],
    object: [{
        type: 'object',
        name: 'My Object',
        shortname: 'object#234',
        enabled: true,
        description: 'This is a description of my object',
        id: '234',
    },
    {
        type: 'object',
        name: 'My Object',
        shortname: 'object#234',
        enabled: true,
        description: 'This is a description of my object',
        id: '234',
    },
    {
        type: 'object',
        name: 'My Object',
        shortname: 'object#234',
        enabled: true,
        description: 'This is a description of my object',
        id: '234',
    }],
    character: [{
        type: 'character',
        name: 'My Character',
        shortname: 'character#234',
        enabled: true,
        description: 'This is a description of my character',
        inventory: [],
        id: '234',
    }],
    mob: [{
        type: 'mob',
        name: 'My Mob',
        shortname: 'mob#234',
        enabled: true,
        description: 'This is a description of my mob',
        inventory: [],
        id: '234',
    },
    {
        type: 'mob',
        name: 'My Mob',
        shortname: 'mob#234',
        enabled: true,
        description: 'This is a description of my mob',
        inventory: [],
        id: '234',
    },
    {
        type: 'mob',
        name: 'My Mob',
        shortname: 'mob#234',
        enabled: true,
        description: 'This is a description of my mob',
        inventory: [],
        id: '234',
    }],
    npc: [{
        type: 'npc',
        name: 'My NPC',
        shortname: 'npc#234',
        enabled: true,
        description: 'This is a description of my NPC',
        inventory: [],
        id: '234',
    },
    {
        type: 'npc',
        name: 'My NPC',
        shortname: 'npc#234',
        enabled: true,
        description: 'This is a description of my NPC',
        inventory: [],
        id: '234',
    },
    {
        type: 'npc',
        name: 'My NPC',
        shortname: 'npc#234',
        enabled: true,
        description: 'This is a description of my NPC',
        inventory: [],
        id: '234',
    },
    {
        type: 'npc',
        name: 'My NPC',
        shortname: 'npc#234',
        enabled: true,
        description: 'This is a description of my NPC',
        inventory: [],
        id: '234',
    }]
  };